---
swagger: "2.0"
info:
  description: "ATTX uvprov internal API for extracting provenance related information from UnifiedViews."
  version: "0.1"
  title: "ATTX uvprovAPI"
  contact:
    name: "ATTX project"
    url: "https://www.helsinki.fi/en/projects/attx-2016"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "uvprovAPI"
  description: "Internal UnifiedViews Provenance API for extracting provenance related information"
  externalDocs:
    description: "just use it"
    url: "https://attx-project.github.io/"
schemes:
- "http"

paths:
  /health:
    get:
      description: "Get health of UVprov-API. Also determined if the database is accessible."
      responses:
        200:
          description: "Successful response."
  /{apiversion}/activity:
    get:
      tags:
      - "uvprovAPI"
      summary: "Retrieve the latest activity and associated datasets.\n"
      description: "This operation gathers all the information necessary to describe\
        \ the activities, datasets and how the datasets are acquired (input dataset)\
        \ or produced (output dataset).\n"
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - name: "modifiedSince"
        in: "query"
        description: "Date since last check."
        required: false
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "Successful response."
        204:
          description: "No Content."
        304:
          description: "Not Changed."
      x-tags:
      - tag: "uvprovAPI"
  /{apiversion}/workflow:
    get:
      tags:
      - "uvprovAPI"
      summary: "List the latest workflow and associated steps.\n"
      description: "This operation gathers all the information necessary to describe\
        \ the workflows, steps and relationships between them\n"
      produces:
      - "application/json"
      parameters:
      - name: apiversion
        in: path
        required: true
        type: "integer"
      - name: "modifiedSince"
        in: "query"
        description: "Date since last check."
        required: false
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "Successful response."
        204:
          description: "No Content."
        304:
          description: "Not Changed."
      x-tags:
      - tag: "uvprovAPI"
definitions: {}
